In [1]:
import pandas as pd

In [2]:
restored_df = pd.read_parquet(
    "/Users/mrutulasuresh/Documents/GitHub/retail-customer-analytics/data/processed/online_retail.parquet"
)

In [3]:
df = restored_df.copy()

In [4]:
print(f"No of rows: {restored_df.shape[0]}")

No of rows: 1033036

In [5]:
restored_df.shape

(1033036, 8)

In [6]:
restored_df.dtypes

Invoice                   str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID               str
Country                   str
dtype: object

In [7]:
restored_df.isnull().sum()

Invoice             0
StockCode           0
Description      4275
Quantity            0
InvoiceDate         0
Price               0
Customer ID    235151
Country             0
dtype: int64

In [8]:
restored_df[restored_df['Customer ID'].isnull()].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
462,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
569,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom

In [9]:
restored_df['Invoice'].value_counts() # Invoice starting with C are credits

Invoice
573585     1114
581219      749
581492      731
580729      721
558475      705
           ...
581487        1
581491        1
C581499       1
581566        1
C581568       1
Name: count, Length: 53628, dtype: int64

In [10]:
restored_df.describe()

           Quantity                    InvoiceDate         Price
count  1.033036e+06                        1033036  1.033036e+06
mean   1.007688e+01  2011-01-03 14:30:35.429549824  4.613980e+00
min   -8.099500e+04            2009-12-01 07:45:00 -5.359436e+04
25%    1.000000e+00            2010-07-05 11:38:00  1.250000e+00
50%    3.000000e+00            2010-12-09 13:34:00  2.100000e+00
75%    1.000000e+01            2011-07-27 13:17:00  4.150000e+00
max    8.099500e+04            2011-12-09 12:50:00  3.897000e+04
std    1.751976e+02                            NaN  1.223975e+02

In [11]:
# negative quantity and price
restored_df[restored_df['Price'] < 0].head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
177338,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
273025,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
398731,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
794040,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
794041,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [12]:
restored_df[restored_df['Quantity'] < 0].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321,Australia

In [13]:
restored_df['Invoice'].str[0].value_counts()

Invoice
5    906634
4    107292
C     19104
A         6
Name: count, dtype: int64

In [14]:
restored_df[restored_df['Invoice'].str[0] == 'A']

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
177338,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36,NaN,United Kingdom
273025,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79,NaN,United Kingdom
398731,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87,NaN,United Kingdom
794039,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom
794040,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
794041,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [ ]:
restored_df['Country'].value_counts()

Country
United Kingdom          948321
EIRE                     17667
Germany                  17339
France                   14025
Netherlands               5137
Spain                     3754
Switzerland               3175
Belgium                   3110
Portugal                  2528
Australia                 1890
Channel Islands           1646
Italy                     1507
Sweden                    1362
Norway                    1308
Cyprus                    1157
Finland                   1049
Austria                    938
Denmark                    797
Unspecified                752
Greece                     663
Japan                      565
USA                        535
Poland                     527
United Arab Emirates       500
Israel                     368
Hong Kong                  360
Singapore                  346
Malta                      299
Canada                     228
Iceland                    222
RSA                        169
Lithuania                  154
Bahrain                    126
Brazil                      94
Thailand                    76
Korea                       63
European Community          61
Lebanon                     58
West Indies                 54
Bermuda                     34
Nigeria                     32
Czech Republic              30
Saudi Arabia                10
Name: count, dtype: int64

In [16]:
restored_df['StockCode'].str.len().value_counts()

StockCode
5     901941
6     123859
4       2122
1       1672
3       1425
7       1346
2        278
12       200
8        126
9         67
Name: count, dtype: int64

In [17]:
restored_df[restored_df['StockCode'].str.len() == 1]['StockCode'].value_counts()

StockCode
M    1387
D     173
S     101
B       6
m       5
Name: count, dtype: int64

In [18]:
restored_df[restored_df['StockCode'].str.len() == 1][['Description', 'StockCode']].value_counts()

Description      StockCode
Manual           M            1387
Discount         D             173
SAMPLES          S             101
Adjust bad debt  B               6
Manual           m               5
Name: count, dtype: int64

1) Customer with Null Id cant be assigned a category so we drop those records
2) Cancellations: the Invoice starts with "C". Move them to a separate returns table. They feed the return-rate feature and are never counted as purchases. reason when we count price we might accidentally count cancellations as well. we might accidentally treat it as a purchase.
3) StockCode : range from 1 to 12 (no 10) use description to decide if we need to remove it 
4) Null descriptions: check if it can be updated from other product descrtiption based on stockcode
5) Line Total: Quantity * Price

In [19]:
original_num = 1033036
df = restored_df.copy()

### Remove Customer with Null ID

In [20]:
restored_df = restored_df[~restored_df['Customer ID'].isnull()]

In [21]:
print(f"No of rows present after removing customers with Null ID {restored_df.shape[0]}. Percentage of rows remaining: {restored_df.shape[0]*100/original_num}")

No of rows present after removing customers with Null ID 797885. Percentage of rows remaining: 77.23690171494508

### Move Cancellations to another table

In [22]:
return_df = restored_df[restored_df['Invoice'].str[0] == 'C']
restored_df = restored_df[restored_df['Invoice'].str[0] != 'C']

In [23]:
return_df.shape[0]

18390

In [24]:
df[(df['Invoice'].str[0] == 'C') & (df['Customer ID'].isnull())].shape[0]

714

In [25]:
print(f"No of rows present after removing customers with Null ID {restored_df.shape[0]}. Percentage of rows remaining: {restored_df.shape[0]*100/original_num}")

No of rows present after removing customers with Null ID 779495. Percentage of rows remaining: 75.4567120603735

### StockCode Analysis

In [26]:
restored_df[restored_df['StockCode'].str.len() == 1][['Description', 'StockCode']].value_counts()

Description  StockCode
Manual       M            688
Discount     D              5
Name: count, dtype: int64

In [27]:
restored_df[restored_df['StockCode'] == 'M'].head(3) #504700

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
11193,490300,M,Manual,1,2009-12-04 14:19:00,0.85,12970,United Kingdom
11194,490300,M,Manual,1,2009-12-04 14:19:00,0.21,12970,United Kingdom
15906,490727,M,Manual,1,2009-12-07 16:38:00,0.00,17231,United Kingdom

In [28]:
restored_df[restored_df['Invoice'] == '490300'].head(20) #Clearly M is a part of another invoice so can be removed

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
11178,490300,21929,JUMBO BAG PINK VINTAGE PAISLEY,1,2009-12-04 14:19:00,1.95,12970,United Kingdom
11179,490300,21726,MULTI HEARTS STICKERS,1,2009-12-04 14:19:00,0.85,12970,United Kingdom
11180,490300,21725,SWEETIES STICKERS,1,2009-12-04 14:19:00,0.85,12970,United Kingdom
11181,490300,22210,WOOD STAMP SET BEST WISHES,1,2009-12-04 14:19:00,1.65,12970,United Kingdom
11182,490300,21731,RED TOADSTOOL LED NIGHT LIGHT,1,2009-12-04 14:19:00,1.65,12970,United Kingdom
11183,490300,10125,MINI FUNKY DESIGN TAPES,2,2009-12-04 14:19:00,0.85,12970,United Kingdom
11184,490300,21790,VINTAGE SNAP CARDS,1,2009-12-04 14:19:00,0.85,12970,United Kingdom
11185,490300,20976,12 PENCILS SMALL TUBE POSY,1,2009-12-04 14:19:00,0.65,12970,United Kingdom
11186,490300,20975,12 PENCILS SMALL TUBE RED SPOTTY,1,2009-12-04 14:19:00,0.65,12970,United Kingdom
11187,490300,20974,12 PENCILS SMALL TUBE SKULL,1,2009-12-04 14:19:00,0.65,12970,United Kingdom
11188,490300,21791,VINTAGE HEADS AND TAILS CARD GAME,2,2009-12-04 14:19:00,1.25,12970,United Kingdom
11189,490300,22139,RETRO SPOT TEA SET CERAMIC 11 PC,1,2009-12-04 14:19:00,4.95,12970,United Kingdom
11190,490300,22149,FELTCRAFT 6 FLOWER FRIENDS,1,2009-12-04 14:19:00,2.10,12970,United Kingdom
11191,490300,21577,SAVE THE PLANET COTTON TOTE BAG,1,2009-12-04 14:19:00,2.25,12970,United Kingdom
11192,490300,21499,BLUE SPOTS WRAP,25,2009-12-04 14:19:00,0.42,12970,United Kingdom
11193,490300,M,Manual,1,2009-12-04 14:19:00,0.85,12970,United Kingdom
11194,490300,M,Manual,1,2009-12-04 14:19:00,0.21,12970,United Kingdom
11195,490300,22079,RIBBON REEL HEARTS DESIGN,1,2009-12-04 14:19:00,1.65,12970,United Kingdom
11196,490300,84466,TOP SECRET PEN SET,2,2009-12-04 14:19:00,1.25,12970,United Kingdom
11197,490300,22075,6 RIBBONS ELEGANT CHRISTMAS,1,2009-12-04 14:19:00,1.65,12970,United Kingdom

In [29]:
d_invoices = restored_df.loc[restored_df['StockCode'] == 'M', 'Invoice'].unique()
restored_df[restored_df['Invoice'].isin(d_invoices)]['Invoice'].value_counts() # no it doesnt look like a transaction

Invoice
567183    392
572103    196
561894    188
580956    184
581405    180
         ...
575043      1
575636      1
576389      1
577068      1
577906      1
Name: count, Length: 626, dtype: int64

In [30]:
d_invoices = restored_df.loc[restored_df['StockCode'] == 'D', 'Invoice'].unique()
restored_df[restored_df['Invoice'].isin(d_invoices)]['Invoice'].value_counts() # no it doesnt look like a transaction

Invoice
504700    1
509979    1
519808    1
535657    1
536158    1
Name: count, dtype: int64

Clearly Carriage isnt a transaction and should be removed

In [31]:
restored_df[restored_df['StockCode'].str.len() == 2][['Description', 'StockCode']].value_counts()

Description  StockCode
CARRIAGE     C2           248
Name: count, dtype: int64

In [32]:
restored_df[restored_df['StockCode'].str.len() == 2].groupby(by='StockCode').agg(
    quantity_mean = ("Quantity", "mean"),
    quantity_min = ("Quantity", "min"),
    quantity_max = ("Quantity", "max"),
    price_mean = ("Price", "mean"),
    price_min = ("Price", "min"),
    price_max = ("Price", "max")
).reset_index()

,StockCode,quantity_mean,quantity_min,quantity_max,price_mean,price_min,price_max
0,C2,1.004032,1,2,50.516129,18.0,150.0

In [33]:
C2_invoices = restored_df.loc[restored_df['StockCode'] == 'C2', 'Invoice'].unique()
restored_df[restored_df['Invoice'].isin(C2_invoices)]['Invoice'].value_counts() # carriage charge can be part of a main invoice or alone

Invoice
572069    43
492092    42
516119    42
531437    42
500123    40
          ..
517485     1
536019     1
539688     1
564085     1
565474     1
Name: count, Length: 248, dtype: int64

StockCode 3 looks like online sales

In [34]:
restored_df[restored_df['StockCode'].str.len() == 3][['Description', 'StockCode']].value_counts()

Description     StockCode
DOTCOM POSTAGE  DOT          16
Name: count, dtype: int64

In [35]:
df[df["StockCode"] == "DOT"].groupby("Price").size()

Price
0.00       7
0.35       1
1.66       1
2.29       1
2.51       1
          ..
2028.25    1
2114.00    1
2196.67    1
2275.54    1
4505.17    1
Length: 1291, dtype: int64

In [36]:
restored_df[restored_df['StockCode'].str.len() == 3].groupby(['StockCode']).agg(
    quantity_mean = ('Quantity', 'mean'),
    quantity_min = ("Quantity", "min"),
        quantity_max = ("Quantity", "max"),
        price_mean = ("Price", "mean"),
        price_min = ("Price", "min"),
        price_max = ("Price", "max")
)

,quantity_mean,quantity_min,quantity_max,price_mean,price_min,price_max
StockCode,,,,,,
DOT,1.0,1,1,744.1475,11.17,1599.26

In [37]:
restored_df[restored_df['StockCode'].str.len() == 3].tail()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
947662,575607,DOT,DOTCOM POSTAGE,1,2011-11-10 12:37:00,908.16,14096,United Kingdom
959667,576339,DOT,DOTCOM POSTAGE,1,2011-11-14 15:27:00,1500.36,14096,United Kingdom
986515,578270,DOT,DOTCOM POSTAGE,1,2011-11-23 13:39:00,1270.06,14096,United Kingdom
999956,579196,DOT,DOTCOM POSTAGE,1,2011-11-28 15:54:00,1526.76,14096,United Kingdom
1019335,580727,DOT,DOTCOM POSTAGE,1,2011-12-05 17:17:00,1599.26,14096,United Kingdom

In [38]:

DOT_invoices = restored_df.loc[restored_df['StockCode'] == 'DOT', 'Invoice'].unique()
restored_df[restored_df['Invoice'].isin(DOT_invoices)]['Invoice'].value_counts() # DOT is a part of main invoices

Invoice
576339    542
579196    533
580727    529
578270    442
573576    435
567656    421
575607    377
571441    364
570488    353
572552    352
568346    335
569246    285
566566     70
566217     34
565383     19
564764      6
Name: count, dtype: int64

Not sure what PADS are but there is a transaction with 0 price and POST is postage looks like carriage charge?

In [39]:
restored_df[restored_df['StockCode'].str.len() == 4][['Description', 'StockCode']].value_counts()

Description                 StockCode
POSTAGE                     POST         1803
PADS TO MATCH ALL CUSHIONS  PADS           18
Name: count, dtype: int64

In [40]:
restored_df[restored_df['StockCode'].str.len() == 4].groupby("StockCode").agg(
    quantity_mean = ('Quantity', 'mean'),
        quantity_min = ("Quantity", "min"),
            quantity_max = ("Quantity", "max"),
            price_mean = ("Price", "mean"),
            price_min = ("Price", "min"),
            price_max = ("Price", "max")
)

,quantity_mean,quantity_min,quantity_max,price_mean,price_min,price_max
StockCode,,,,,,
PADS,1.000000,1,1,0.000944,0.0,0.001
POST,2.903494,1,21,29.938874,1.0,8142.750

In [41]:
restored_df[(restored_df['StockCode'].str.len() == 4)&(restored_df['StockCode'] == 'PADS') & (restored_df['Price'] == 0)].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
852311,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,2011-09-25 12:22:00,0.0,16133,United Kingdom

In [42]:
POST_invoices = restored_df.loc[restored_df['StockCode'] == 'POST', 'Invoice'].unique()
restored_df[restored_df['Invoice'].isin(POST_invoices)]['Invoice'].value_counts() # POST are also part of other invoice or alone

Invoice
540458    149
514387    135
573362    116
507660    111
495310    110
         ...
575888      1
578123      1
578425      1
579790      1
580706      1
Name: count, Length: 1803, dtype: int64

In [43]:
PADS_invoices = restored_df.loc[restored_df['StockCode'] == 'PADS', 'Invoice'].unique()
restored_df[restored_df['Invoice'].isin(PADS_invoices)]['Invoice'].value_counts() # cPADS are also part of other invoice

Invoice
550193    93
499399    76
501176    56
504332    45
496222    43
531433    38
533528    30
568158    25
497935    24
496473    21
494914    20
496643    20
506303    20
498562    19
499056    17
522766    16
568200    15
561226    12
Name: count, dtype: int64

Bank charges arent actual transaction and should be removed

In [44]:
restored_df[restored_df['StockCode'].str.len() == 12][['Description', 'StockCode']].value_counts()

Description    StockCode
Bank Charges   BANK CHARGES    29
 Bank Charges  BANK CHARGES     2
Name: count, dtype: int64

In [45]:
restored_df[restored_df['StockCode'].str.len() == 12].groupby("StockCode").agg(
    quantity_mean = ('Quantity', 'mean'),
        quantity_min = ("Quantity", "min"),
            quantity_max = ("Quantity", "max"),
            price_mean = ("Price", "mean"),
            price_min = ("Price", "min"),
            price_max = ("Price", "max")
)

,quantity_mean,quantity_min,quantity_max,price_mean,price_min,price_max
StockCode,,,,,,
BANK CHARGES,1.0,1,1,14.516161,0.001,15.0

In [46]:
restored_df[(restored_df['StockCode'].str.len() == 12)].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
18259,490948,BANK CHARGES,Bank Charges,1,2009-12-08 14:29:00,15.0,16805,United Kingdom
93392,498269,BANK CHARGES,Bank Charges,1,2010-02-17 15:03:00,15.0,16928,United Kingdom
146414,503497,BANK CHARGES,Bank Charges,1,2010-04-01 12:07:00,15.0,17539,United Kingdom
151831,503960,BANK CHARGES,Bank Charges,1,2010-04-08 16:50:00,15.0,12843,United Kingdom
165500,505204,BANK CHARGES,Bank Charges,1,2010-04-20 16:24:00,15.0,17448,United Kingdom

In [47]:
BANK_invoices = restored_df.loc[restored_df['StockCode'] == 'BANK CHARGES', 'Invoice'].unique()
restored_df[restored_df['Invoice'].isin(BANK_invoices)]['Invoice'].value_counts() # Only 1 is part of anotehr invoice rest alone

Invoice
568375    2
490948    1
498269    1
503497    1
503960    1
505204    1
509375    1
509669    1
511774    1
512658    1
515845    1
515855    1
517648    1
517652    1
518666    1
518667    1
521809    1
521812    1
532637    1
535474    1
536779    1
541505    1
549717    1
551945    1
565735    1
571900    1
573586    1
574546    1
579137    1
581127    1
Name: count, dtype: int64

In [48]:
codes = ["M", 'D', "C2", "DOT", "POST", "PADS", "BANK CHARGES"]

restored_df[restored_df["StockCode"].isin(codes)].groupby(
    ["StockCode", "Description"]
).agg(
    rows=("StockCode", "size"),
    total_quantity=("Quantity", "sum"),
    min_price=("Price", "min"),
    max_price=("Price", "max"),
    customers=("Customer ID", "nunique")
).sort_index()

                                         rows  total_quantity  min_price  \
StockCode    Description
BANK CHARGES  Bank Charges                  2               2     15.000
             Bank Charges                  29              29      0.001
C2           CARRIAGE                     248             249     18.000
D            Discount                       5             196      1.000
DOT          DOTCOM POSTAGE                16              16     11.170
M            Manual                       688            9391      0.000
PADS         PADS TO MATCH ALL CUSHIONS    18              18      0.000
POST         POSTAGE                     1803            5235      1.000

                                         max_price  customers
StockCode    Description
BANK CHARGES  Bank Charges                  15.000          2
             Bank Charges                   15.000         18
C2           CARRIAGE                      150.000         45
D            Discount                      101.990          5
DOT          DOTCOM POSTAGE               1599.260          1
M            Manual                      10953.500        443
PADS         PADS TO MATCH ALL CUSHIONS      0.001         16
POST         POSTAGE                      8142.750        405

Cleaning decision
1) BANK CHARGES - Almost always standalone and doesnt look like a transaction - REMOVE
2) CARRIAGE - Mostly with other invoices - not a transation - REMOVE
3) Discount - only 5 records with standalone invoices - not a transaction - REMOVE
4) DOTCOM POSTAGE - Always with other transation - not a transaction - REMOVE 
5) Manual - Almost alwyas with other transaction - not a transation - REMOVE
6) PADS - padding related always with other invoice - not a transtion - REMOVE
7) POST - Posting related - not a transtion - REMOVE

In [49]:
before_removing_stockcode = restored_df.shape[0]

In [50]:
restored_df = restored_df[~restored_df['StockCode'].isin(['BANK CHARGES', 'C2', 'D','M', 'DOT', 'PADS', 'POST'])]

In [51]:
print(f"Before stockcode removing: {before_removing_stockcode}. After removing: {restored_df.shape[0]}. Percentage reduced: {(before_removing_stockcode - restored_df.shape[0])/before_removing_stockcode}")

Before stockcode removing: 779495. After removing: 776686. Percentage reduced: 0.0036036151610978904

In [52]:
restored_df[restored_df['Price'] == 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
4607,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126,United Kingdom
6702,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658,United Kingdom
18531,490961,22065,CHRISTMAS PUDDING TRINKET POT,1,2009-12-08 15:25:00,0.0,14108,United Kingdom
18532,490961,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-08 15:25:00,0.0,14108,United Kingdom
32543,492079,85042,ANTIQUE LILY FAIRY LIGHTS,8,2009-12-15 13:49:00,0.0,15070,United Kingdom
...,...,...,...,...,...,...,...,...
946872,575579,22437,SET OF 9 BLACK SKULL BALLOONS,20,2011-11-10 11:49:00,0.0,13081,United Kingdom
946873,575579,22089,PAPER BUNTING VINTAGE PAISLEY,24,2011-11-10 11:49:00,0.0,13081,United Kingdom
971149,577129,22464,HANGING METAL HEART LANTERN,4,2011-11-17 19:52:00,0.0,15602,United Kingdom
972694,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,2011-11-18 13:23:00,0.0,12444,Norway
993788,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.0,13256,United Kingdom

In [53]:
invoice_price_0 = restored_df.loc[restored_df['Price'] == 0, 'Invoice']
df[df['Invoice'].isin(invoice_price_0)]['Invoice'].value_counts()

Invoice
540372    171
577314     35
539722     29
493899     28
521375     27
532470     26
493761     24
550188     23
547417     22
574920     22
539263     21
505083     20
524701     20
533822     20
489998     18
511902     18
518231     18
503585     17
537197     17
492079     15
524181     14
569716     14
500073     13
527696     13
492760     12
489825     11
516304     11
531361     11
490961     10
562973     10
561669      8
572893      8
548318      7
548871      7
561284      6
574138      5
527084      4
553000      4
554037      4
564651      4
494607      3
574175      3
574879      3
575579      3
512609      2
513416      2
541109      2
574469      2
577129      2
497819      1
497843      1
543599      1
578841      1
Name: count, dtype: int64

In [54]:
filtered_df = df[df['Invoice'].isin(invoice_price_0)]
filtered_df[filtered_df.groupby('Invoice').transform("size") == 1]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
88112,497819,TEST001,This is a test product.,5,2010-02-12 14:58:00,0.0,14103,United Kingdom
88207,497843,TEST001,This is a test product.,5,2010-02-12 15:47:00,0.0,14827,United Kingdom
582376,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,2011-02-10 13:08:00,0.0,17560,United Kingdom
993788,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.0,13256,United Kingdom

In [55]:
restored_df.loc[restored_df['Price'] < 0]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

Majority of records with Price = 0 are part of another invoice so must be a free item or wrong price. There are no negative price records and hence we can remove it

In [56]:
size_before_price_removal = restored_df.shape[0]

In [57]:
restored_df = restored_df[restored_df['Price'] != 0]

In [58]:
print(f"Before stockcode removing: {size_before_price_removal}. After removing: {restored_df.shape[0]}. Percentage reduced: {(size_before_price_removal - restored_df.shape[0])/size_before_price_removal}")

Before stockcode removing: 776686. After removing: 776624. Percentage reduced: 7.982633908683818e-05

In [ ]:
restored_df['line_value'] = restored_df['Quantity'] * restored_df['Price']

Write the processed transaction data and cancellation data as a parque file

In [60]:
restored_df.to_parquet("/Users/mrutulasuresh/Documents/GitHub/retail-customer-analytics/data/processed/transaction_data.parquet",
                        engine='pyarrow', index=False, compression = 'snappy')

In [61]:
return_df['line_value'] = return_df['Quantity'] * return_df['Price']

In [62]:
return_df = return_df[~return_df['StockCode'].isin(['BANK CHARGES', 'C2', 'D','M', 'DOT', 'PADS', 'POST'])]

In [66]:
return_df[return_df['Price'] < 0]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country, line_value]
Index: []

In [65]:
return_df.shape[0]

17635

In [64]:
return_df.to_parquet("/Users/mrutulasuresh/Documents/GitHub/retail-customer-analytics/data/processed/returns_data.parquet",
                        engine='pyarrow', index=False, compression = 'snappy')

In [70]:
invoice_country_check = (
    restored_df
    .groupby('Invoice')['Country']
    .nunique()
)

In [71]:
print(invoice_country_check[
    invoice_country_check > 1
])

Series([], Name: Country, dtype: int64)